//go:build e2e

// Adversarial E2E: idempotency (assumptions A1, A2, A3, A4).
//
// These run against a REAL Forgejo instance (see harness.FromEnv) because the
// assumptions under attack are exactly the ones httptest mocks cannot falsify:
// whether Forgejo's issue list filters by label *name* (A1), whether the hidden
// HTML-comment dedup marker survives a create→list round-trip through Forgejo's
// storage (A2), and whether wiki re-publishes are true no-ops (A3).
package forgejoe2e

import (
	"context"
	"testing"
	"time"

	"github.com/Warlockobama/DevSecOpsKB/zap-kb/internal/e2e/forgejo/harness"
	"github.com/Warlockobama/DevSecOpsKB/zap-kb/internal/output/forgejo"
)

// A1+A2+A4: re-publishing the same entities must create zero new issues. This
// fails if the `?labels=kb-finding` dedup query silently returns nothing (A1),
// if Forgejo mangles the hidden marker (A2), or if finding IDs drift between
// runs (A4).
func TestRepublishCreatesNoDuplicates(t *testing.T) {
	env := harness.FromEnv(t)
	repo := env.CreateRepo(t, true)
	ef := harness.Fixture(harness.FixtureOptions{NumHighFindings: 3})
	opts := forgejo.Options{
		BaseURL: env.BaseURL, Token: env.Token, Owner: env.Owner, Repo: repo,
		MinRisk: "medium",
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	first, err := forgejo.Export(ctx, ef, opts)
	if err != nil {
		t.Fatalf("first export: %v", err)
	}
	if first.Created != 3 || first.Errors != 0 {
		t.Fatalf("first export: created=%d errors=%d, want 3/0", first.Created, first.Errors)
	}

	// A2: the marker must be recoverable from what the server stored.
	issues := env.ListIssues(t, repo)
	if len(issues) != 3 {
		t.Fatalf("after first export: %d issues, want 3", len(issues))
	}
	markers := map[string]bool{}
	for _, iss := range issues {
		fid := harness.MarkerFindingID(iss.Body)
		if fid == "" {
			t.Errorf("A2 VIOLATED: issue #%d body lost the dedup marker; re-runs will duplicate it", iss.Number)
		}
		markers[fid] = true
	}

	// A1: second run must dedup via the label-name query against the live API.
	second, err := forgejo.Export(ctx, ef, opts)
	if err != nil {
		t.Fatalf("second export: %v", err)
	}
	if second.Created != 0 || second.Skipped != 3 {
		t.Errorf("A1 VIOLATED: second export created=%d skipped=%d, want 0/3 — label-name dedup query is not finding existing issues", second.Created, second.Skipped)
	}
	if got := env.ListIssues(t, repo); len(got) != 3 {
		t.Errorf("A1/R7 VIOLATED: %d issues after re-publish, want 3 (duplicates created)", len(got))
	}

	// A4: ticket refs must be identical run-to-run (stable IDs, stable dedup).
	for fid, ref := range first.TicketRefs {
		if second.TicketRefs[fid] != ref {
			t.Errorf("A4 VIOLATED: ticket ref for %s changed across runs: %q → %q", fid, ref, second.TicketRefs[fid])
		}
	}
}

// A3 (layer fix 3): re-publishing an unchanged vault must be a no-op — all
// pages "skipped", none "updated" — so the wiki's git history does not grow on
// every CronJob tick.
func TestWikiRepublishIsNoOp(t *testing.T) {
	env := harness.FromEnv(t)
	repo := env.CreateRepo(t, true)
	vault := t.TempDir()
	harness.WriteVault(t, vault, map[string]string{
		"INDEX.md":          "# KB Home\n\nGenerated by e2e.",
		"findings/fin-1.md": "# Finding 1\n\nEvidence here.",
	})
	opts := forgejo.WikiOptions{BaseURL: env.BaseURL, Token: env.Token, Owner: env.Owner, Repo: repo}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	first, err := forgejo.ExportWiki(ctx, vault, opts)
	if err != nil {
		t.Fatalf("first wiki export: %v", err)
	}
	if first.Created != 2 || first.Errors != 0 {
		t.Fatalf("first wiki export: created=%d errors=%d, want 2/0", first.Created, first.Errors)
	}

	second, err := forgejo.ExportWiki(ctx, vault, opts)
	if err != nil {
		t.Fatalf("second wiki export: %v", err)
	}
	if second.Skipped != 2 || second.Updated != 0 || second.Created != 0 {
		t.Errorf("A3 VIOLATED: second wiki export created=%d updated=%d skipped=%d, want 0/0/2 — unchanged pages are being rewritten every run", second.Created, second.Updated, second.Skipped)
	}
}
